# Proposal
 
 Recession is said to occur when there is constant fall in GDP of a country for two consecutive quarters. While some economists say when overall "economy" is not doing well. However, there are no specific factors to laid out which are defined to identify if a country is under recession. We want to propose a solution to this problem using EDA.Specifically, we want to use EDA on data available on years in which recession occurred and analyze co-relating factors contributing to the recession. (Specific to USA).In other words, we want to perform EDA to be able pinpoint specific factors which clearly indicates that a recession in going occur.
 
## Research topic

Factors Contributing to a Recession


## Data availability

For finding features contributing to recession we will be using different financial datasets combined together in which the target variable will represent the period of expansion or recession. For the target variable, the value “1” will represent a period of recession and the value “0” will represent a period of expansion. This time series is an interpretation of US Business Cycle Expansions and Contractions data provided by The National Bureau of Economic Research (NBER). The dataset has a frequency of a month. 

For identifying the possible features, we are using 6 different time series which will form the final dataset after combining all the time series together.

1. 3 months Bill rate: This is a 3-Months Treasury Bill Secondary Market Rate.
The dataset can be retrieved from FRED, Federal Reserve Bank of St. Louis.
The source of the dataset is the Board of Governors of the Federal Reserve System (US).

Update frequency: Monthly.

Citation: Board of Governors of the Federal Reserve System (US), 3-Month Treasury Bill Secondary Market Rate, Discount Basis [TB3MS], retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/TB3MS, October 30, 2022.

2. Capacity Utilization, Manufacturing: This is a Capacity Utilization of the manufacturing sector in the USA. 
The capacity utilization rate for a particular industry is equal to an output index divided by a capacity index. The Federal Reserve Board's capacity indexes attempt to capture the concept of sustainable maximum output-the greatest level of output a plant can maintain within the framework of a realistic work schedule, after factoring in normal downtime and assuming sufficient availability of inputs to operate the capital in place.
The dataset can be retrieved from  FRED, Federal Reserve Bank of St. Louis.
The source of the dataset is the Board of Governors of the Federal Reserve System (US).
Update frequency: Monthly.

Citation: Board of Governors of the Federal Reserve System (US), Capacity Utilization: Manufacturing (SIC) [CUMFNS], retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/CUMFNS, October 30, 2022.

3. Industrial Production: The industrial production (IP) index measures the real output of all relevant establishments located in the United States, regardless of their ownership, but not those located in U.S. territories.
The dataset can be retrieved from FRED,  Federal Reserve Bank of St. Louis.
The source of the dataset is the Board of Governors of the Federal Reserve System (US).
Update frequency: Monthly.

Citation: Board of Governors of the Federal Reserve System (US), Industrial Production: Total Index [INDPRO], retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/INDPRO, October 30, 2022.

4. CPI Index: is a measure of the average change over time in the prices paid by urban consumers for a market basket of consumer goods and services. Indexes are available for the U.S. and various geographic areas. Average price data for select utility, automotive fuel, and food items are also available.

The dataset can be retrieved from FRED, Federal Reserve Bank of St. Louis.
The source of the dataset is the Board of Governors of the Federal Reserve System (US).
Update frequency: Monthly.

Citation: U.S. Bureau of Labor Statistics, Consumer Price Index for All Urban Consumers: All Items in U.S. City Average [CPIAUCNS], retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/CPIAUCNS, October 30, 2022.

5. 10 Years Rate: Averages of business days. For further information regarding treasury constant maturity data, please refer to the H.15 Statistical Release notes and the Treasury Yield Curve Methodology.

The dataset can be retrieved from FRED the economic database of the Federal Reserve of St. Louis.

The source of the dataset is the Board of Governors of the Federal Reserve System (US).
Update frequency: Monthly.

Citation: Board of Governors of the Federal Reserve System (US), Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis [GS10], retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/GS10, October 30, 2022.


6. Unemployment Rate: The unemployment rate represents the number of unemployed as a percentage of the labor force. Labor force data are restricted to people 16 years of age and older, who currently reside in 1 of the 50 states or the District of Columbia, who do not reside in institutions (e.g., penal and mental facilities, homes for the aged), and who are not on active duty in the Armed Forces.
The dataset can be retrieved from FRED.
The source of the dataset is the U.S. Bureau of Labor Statistics.
Update frequency: Monthly.

Citation: U.S. Bureau of Labor Statistics, Unemployment Rate [UNRATE], retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/UNRATE, December 9, 2022.

7. Recession Indicator: This time series is an interpretation of US Business Cycle Expansions and Contractions data provided by The National Bureau of Economic Research (NBER). Our time series is composed of dummy variables that represent periods of expansion and recession. The NBER identifies months and quarters of turning points without designating a date within the period that turning points occurred. The dummy variable adopts an arbitrary convention that the turning point occurred at a specific date within the period. The arbitrary convention does not reflect any judgment on this issue by the NBER's Business Cycle Dating Committee. A value of 1 is a recessionary period, while a value of 0 is an expansionary period. For this time series, the recession begins the first day of the period following a peak and ends on the last day of the period of the trough.

Citation: 
Federal Reserve Bank of St. Louis, NBER based Recession Indicators for the United States from the Period following the Peak through the Trough [USREC], retrieved from FRED, Federal Reserve Bank of St. Louis; https://fred.stlouisfed.org/series/USREC, December 9, 2022.

## References
1. FRED economic data: https://fred.stlouisfed.org/series/
